# EXERCÍCIO

-- RELATÓRIO GERAL
SELECT * -- USANDO O *, VAI SAIR NA PROJEÇÃO AS COLUNAS DE JUNÇÃO
FROM CLIENTE C 
	left JOIN ENDERECO E 
		ON C.IDCLIENTE = E.ID_CLIENTE	 
	left JOIN TELEFONE T 
		ON C.IDCLIENTE = T.ID_CLIENTE
	ORDER BY T.TIPO, E.ESTADO; -- ORDENAGEM PARA AJUDAR EM OUTRO EXERCICIO
    
-- RELATÓRIO GERAL DOS HOMENS
SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, -- ESPECIFICANDO CADA COLUNA QUE SERÁ PROJETADA, E COMO SERÁ MUITO GRANDE DEVEMOS INDENTAR POR TABALE.
	   E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, 
	   T.TIPO, T.NUMERO
FROM CLIENTE C  
	INNER JOIN ENDERECO E 
		ON C.IDCLIENTE = E.ID_CLIENTE	 
	INNER JOIN TELEFONE T 
		ON C.IDCLIENTE = T.ID_CLIENTE
	WHERE SEXO = 'M';
    
-- CORRIGIR OS IDS: 11,12,13,17,18 PARA FEMININO
	-- 1° FORMA
		SELECT * 
		FROM CLIENTE  
		WHERE IDCLIENTE = 11 OR IDCLIENTE = 12 OR IDCLIENTE = 13 OR IDCLIENTE = 17 OR IDCLIENTE = 18;
    
    -- 2° FORMA
		SELECT * 
		FROM CLIENTE  
		WHERE IDCLIENTE IN (11,12,13,17,18);
        
-- UPDATE DE FATO
	UPDATE CLIENTE
    SET SEXO = 'F'
    WHERE IDCLIENTE IN (11,12,13,17,18);
    
-- RELATÓRIO GERAL DAS MULHERES
SELECT C.IDCLIENTE, C.NOME, C.SEXO, ifnull(C.EMAIL, '*************') as 'EMAIL', C.CPF,  -- UTILIZANDO A FUNÇÃO IFNULL() PARA MODIFICAR OS CAMPOS NULL DO RELATÓRIO
	   E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO
FROM CLIENTE C 
	INNER JOIN ENDERECO E 
		ON C.IDCLIENTE = E.ID_CLIENTE	 
	INNER JOIN TELEFONE T 
		ON C.IDCLIENTE = T.ID_CLIENTE
	WHERE SEXO = 'F';
    
    -- CORRIGIR OS ID: 15 PARA MASCULINO
    
SELECT * FROM CLIENTE WHERE IDCLIENTE = 15;

update CLIENTE
SET SEXO = 'M'
WHERE IDCLIENTE = 15;

-- QNT HOMENS/MULHERES    
SELECT SEXO, COUNT(*) FROM CLIENTE group by SEXO;
SELECT IDCLIENTE,NOME,SEXO FROM CLIENTE; -- 6


-- ID E EMAIL DE MULHERES QUE MORAM NO CENTRO DO RIO DE JANEIRO E QUE NÃO TENHAM CELULAR
SELECT C.IDCLIENTE,C.EMAIL, C.NOME,C.SEXO, T.TIPO,E.BAIRRO,E.CIDADE -- COLOCANDO OUTROS TIPOS SÓ PARA AJUDAR NA CONFERÊNCIA
FROM CLIENTE C 
	LEFT JOIN ENDERECO E 
		ON C.IDCLIENTE = E.ID_CLIENTE 
	LEFT JOIN TELEFONE T 
		ON C.IDCLIENTE = T.ID_CLIENTE 
WHERE E.CIDADE = 'RIO DE JANEIRO' 
	AND E.BAIRRO = 'CENTRO' AND C.SEXO = 'F' AND T.TIPO <> 'CEL'; -- PRECISAMOS SABER SOBRE SUBQUERY PARA RESOLVER ESSE EXERCICIO

-- NOME, EMAIL E NUMERO DOS CELULADRES DOS CLIENTES QUE MORAM ESTADO DORIO DE JANEIRO 
SELECT C.NOME, C.EMAIL, T.NUMERO AS 'NUMERO DO CELULAR', T.TIPO, E.ESTADO -- COLOCANDO OUTROS TIPOS SÓ PARA AJUDAR NA CONFERÊNCIA
FROM CLIENTE C
	INNER JOIN ENDERECO E
		ON C.IDCLIENTE = E.ID_CLIENTE
	INNER JOIN TELEFONE T
		ON C.IDCLIENTE = T.ID_CLIENTE
WHERE E.ESTADO = 'RJ' AND T.TIPO = 'CEL';

-- NOME, EMAIL E NUMERO DOS CELULADRES DAS MULHERES QUE MORAM ESTADO DE SAO PAULO
SELECT C.NOME, C.EMAIL, T.NUMERO AS 'NUMERO DO CELULAR', T.TIPO, E.ESTADO -- COLOCANDO OUTROS TIPOS SÓ PARA AJUDAR NA CONFERÊNCIA
FROM CLIENTE C
	INNER JOIN ENDERECO E
		ON C.IDCLIENTE = E.ID_CLIENTE
	INNER JOIN TELEFONE T
		ON C.IDCLIENTE = T.ID_CLIENTE
WHERE E.ESTADO = 'SP' AND T.TIPO = 'CEL' AND C.SEXO ='F';